// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./types";

let supabase: SupabaseClient | null = null;

export async function getSupabaseClient(): Promise<SupabaseClient> {
  if (supabase) return supabase;
  let url = localStorage.getItem("supabase_url");
  let anon_key = localStorage.getItem("supabase_anon_key");
  if (!url || !anon_key) {
    console.log("[Supabase] Fetching key from backend...");
    const res = await fetch(
      "https://api.stuntingcaresulut.cyou/api/supabase-keys"
    );
    const data = await res.json();
    url = data.url;
    anon_key = data.anon_key;
    localStorage.setItem("supabase_url", url);
    localStorage.setItem("supabase_anon_key", anon_key);
  }
  supabase = createClient(url, anon_key);

  // Cek koneksi Supabase (query ringan)
  try {
    const { error } = await supabase.from("profiles").select("id").limit(1);
    if (error) {
      console.error("[Supabase] Key invalid, reset cache.", error);
      localStorage.removeItem("supabase_url");
      localStorage.removeItem("supabase_anon_key");
      throw new Error(
        "Supabase key invalid, cache direset. Silakan refresh halaman."
      );
    }
  } catch (e) {
    console.error("[Supabase] Gagal koneksi ke Supabase.", e);
    localStorage.removeItem("supabase_url");
    localStorage.removeItem("supabase_anon_key");
    throw new Error(
      "Gagal koneksi ke Supabase. Silakan cek koneksi dan refresh halaman."
    );
  }

  return supabase;
}

// Import the supabase client like this:
// import { getSupabaseClient } from "@/integrations/supabase/client";
