// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sadtnyksdiujxgvwxspc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhZHRueWtzZGl1anhndnd4c3BjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NDI3MzYsImV4cCI6MjA2NTIxODczNn0.DbQczBTxQSAVS03DZYYqwO3_isT8cRMTvHLfQFwhkec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);